spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    data-username: sa
    data-password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

# logging level
logging:
  level:
    org.springframework: ERROR
    com.accela: DEBUG
  file:
    name: app.log


## if no active profile, default is 'default'
##spring.profiles.active=prod

# root level
#logging.level.=INFO
